CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS schema;

CREATE TABLE schema (
  version   INTEGER                  NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO schema (VERSION, TIMESTAMP) VALUES (
  0, NOW());