Vagrant.configure("2") do |config|
  config.vm.guest = :freebsd
  config.vm.box = "freebsd/FreeBSD-11.1-STABLE"
  config.vm.base_mac = "080027D14C66"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true
  config.vm.synced_folder "../..",
                          "/home/vagrant/go/src/github.com/jasonish/evebox",
                          type: "rsync",
                          rsync__exclude: ["**node_modules**"]

  config.ssh.shell = "sh"

  config.vm.network "forwarded_port", guest: 5636, host: 5636,
                    auto_correct: true

  config.vm.provision "shell", inline: <<-SHELL
    pkg install -y \
        go \
        bash \
        curl \
        python2 \
        gmake \
        node \
        npm \
        git \
        zip
   SHELL
end
