name: Builds

on:
  push:
    paths-ignore:
      - "CHANGELOG.md"
      - "README.md"
  pull_request:
    paths-ignore:
      - "CHANGELOG.md"
      - "README.md"

jobs:

  cargo-test:
    name: Cargo Test
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo test --all

  build-dist:
    name: Build Distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash -x ./build-dist.sh
