name: Builds

on:
  push:
    paths-ignore:
      - "CHANGELOG.md"
      - "README.md"
  pull_request:
    paths-ignore:
      - "CHANGELOG.md"
      - "README.md"

jobs:

  cargo-test:
    name: Cargo Test
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
      - uses: actions/checkout@v4
      # Needed to we can get the build revision, required by build.rs
      - run: git config --global --add safe.directory /__w/evebox/evebox
      - run: cargo test --all

  msrv-check:
    name: Check MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract MSRV from Cargo.toml
        id: msrv
        run: |
          MSRV=$(grep '^rust-version' Cargo.toml | sed 's/.*"\(.*\)".*/\1/')
          echo "version=$MSRV" >> $GITHUB_OUTPUT
          echo "Detected MSRV: $MSRV"
      - name: Install Rust ${{ steps.msrv.outputs.version }}
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ steps.msrv.outputs.version }}
      - name: Test with MSRV
        run: cargo test --all

  clippy:
    name: Clippy Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
          targets: x86_64-pc-windows-gnu
      - name: Run clippy
        run: cargo clippy --all --all-targets -- -D warnings
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Run clippy with cross for Windows
        run: cross clippy --all --all-targets --target x86_64-pc-windows-gnu -- -D warnings

  build-dist:
    name: Build Distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash -x ./build-dist.sh
